# About the Lab 

## Mission

The Lab seeks to serve, empower, and equip individuals and communities to answer their questions, meet their objectives, and transform their lives and communities using community-based mixed methods psychological research. We are particularly interested in working with communities traditionally underserved by clinical psychology, and in particular folks and communities affected by conflict, broadly construed. Wherever we work, we strive to do our work with integrity,  humility, and in the context of authentic relationships.

## Vision

We seek to partner with communities and work towards community health and wellness in the world, one community at a time.

## Core Values

These are values that guide and direct our work on a daily basis. By working in the lab, we all agree to work towards these values.

- Humility: We seek to be open to learning new things through trying out and making mistakes. We will own up to mistakes, and learn from them.

- Curiosity: We approach situations as opportunities to learn something new.

- Integrity: We say what we mean and mean what we say. We do what we say we will do and admit when we have made mistakes.

- Relationships: We work towards forming authentic relationships with each other and community partners.

- Persistence: We try, try, and try again.

- Service: We look to the interests of others, including fellow labmates, community partners, and research participants.

- Diversity: We all have different backgrounds and experiences. Through this diversity, we can all learn and get a better perspective. 


## The Communities with whom we Partner

While open to working with a diverse range of communities, we have traditionally worked to improve wellness in conflict-affected populations. Specifically, we have partnered with the following organizations:

- [Christian Action for Reconciliation and Social Assistance (CARSA)](https://www.carsaministry.org/) - a nonprofit organization in Rwanda working to heal communities in the aftermath of the 1994 Rwandan genocide.

- [Working Alongside Refugees in Mental Health (WARM)](warmalska.org) - a network of mental health providers and allied organizations working to train mental health providers to work with forced migrants, like refugees and asylum-seekers.

## Our Collaborators

Our collaborators are a crucial part to the work that we are completing. We believe that science is better (and more enjoyable) when done with partners. Below are a couple of our collaborators:

- [Sara Buckingham, Ph.D.](https://www.uaa.alaska.edu/academics/college-of-arts-and-sciences/departments/psychology/faculty/buckingham.cshtml), and the [Crossroads Research Collective](https://crossroadsresearch.wixsite.com/collective)

- [Ezer Kang, Ph.D.](https://profiles.howard.edu/profile/466/ezer-kang), and the [Global Community Health Lab](https://ezerkang-howard-faculty.com/)

## Our History

Jordan established the lab in 2022 at UW Parkside. Kaylie Garcia and Rachael Hall were inaugural lab members beginning in Spring 2022 and Undergraduate Research Assistants through the [Undergraduate Research Assistantship Program (URAP)](#URAP) in Summer 2022.

## Space and Info

The lab is located at the University of Wisconsin Parkside, and a physical location is MOLN315E. Information about accessing the lab is available from Jordan.

[Lab Wiki](https://rangersuwp.sharepoint.com/sites/NoNameLab)
[Lab Manual](https://bookdown.org/jordandanielsnyder/LabManual/)

PI contact: Jordan Snyder, PsyD

## Joining the Lab

To join the lab, there is a multi-step process. 

1. Send Jordan a lab application. A lab application consists of sending Jordan an email (snyderj@uwp.edu) with the following: (1) what year you will be in the semester/year you want to be an RA, (2) your expected month and year of graduation, (3) whether or not you have completed Statistics and Research Methods, (4) your GPA, (5) why you want to be an RA, and which type of RA you are interested in being (see below for more information, but options are for credit, volunteer, or URAP), (6) what area of psychology is most interesting to you and why, (7) what are your strengths and weaknesses, (8) what are your plans for the future, and (9) anything else you think is relevant. I will respond to your email and let you know if we should have an interview. Please note, there are several ways to join the lab:
  + Join the lab as a volunteer. If you join the lab as a volunteer, you will not get compensated or get academic credit for participating in lab. I ask students who volunteer in lab not to do more than 3-5 hours of lab work per week (inclusive of all meetings).

  + Join the lab for credit. If you join the lab for credit (and Jordan approves this), you will work on a form with Jordan to submit to the registrar. The form will contain a list of obligations/responsibilities for you to complete for a grade. You will get credit for [PSYC499](https://www.uwp.edu/learn/academiccatalog/2019-2021/psyc.cfm#courses#courses). You can get up to 6 credits of PSYC499, with 3 credits counting for upper level electives in the psychology major, and 3 credits counting for upper level electives. If you wish to use 6 credits, I ask that you commit to a full year in the lab (September - May) and use 3 credits per semester. I ask students to expect to work a maximum of 3 hours per week per credit hour (e.g., for 3 credits, you could work up to 9 hours in lab responsibilities per week). However, I don't want you working more than that outside special occasions (e.g., traveling to a conference, etc.). Please note, if you are hoping to conduct one of your own studies, I will evaluate the proposed project to see if I am able to supervise you and I have the resources to help you. If I think that I can supervise you and there are resources, I will instruct to come up with a proposal of the work you hope to conduct and a timeline for your project *BEFORE* we complete the form for the independent study.

  + Join the lab as through [the Undergraduate Research Assistantship Program (URAP)](#URAP). Typically, I encourage students to be in the lab before joining through the URAP program, as these applications are best done once you have been in the lab. There are grants for the Fall and the Spring, as well as a grant for the summer.
  
  + Join the lab through the [American Psychological Association (APA) Summer Undergraduate Psychology Experience in Research Fellowships](https://www.apa.org/about/awards/undergraduate-research-opportunity). This competitive fellowship is for undergraduate students from underrepresented groups interested in psychology research over the summer. Please be in contact with Dr. Snyder about this if you are interested in the Fall semester for the following Summer, as the application is due in the middle of February.

2. Jordan will review these applications on a weekly basis and reach out if he has capacity/availability for a student to schedule an interview. Based upon the application and the interview, he may extend an invitation to join the lab.

3. If you join the lab, you will be expected to do the following:
  + Do the [Onboarding Section](#onboarding) of this lab manual.
  + Fulfill the obligations listed in the expectations role for which you are joining the lab.

4. Jordan will do the following:
  + Add you to the lab sharepoint.
  + Review your individual mentoring plan with you.
